import { ClusterProvider } from '@/components/cluster/cluster-data-access'
import { SolanaProvider } from '@/components/solana/solana-provider'
import { UiLayout } from '@/components/ui/ui-layout'
import { StyledComponents } from '@/lib/registry'
import { TRPCReactProvider } from '@/trpc/react'
import * as React from 'react'
import './globals.css'

export const metadata = {
  title: 'Ezpool',
  description: 'Generated by create-solana-dapp',
}

const links: Array<{ label: string; path: string }> = [
  // { label: 'Account', path: '/account' },
  // { label: 'Clusters', path: '/clusters' },
  { label: 'Ezpool Program', path: '/ezpool' },
  { label: 'Fee Tiers', path: '/fee-tier' },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponents>
          <TRPCReactProvider>
            <ClusterProvider>
              <SolanaProvider>
                <UiLayout links={links}>{children}</UiLayout>
              </SolanaProvider>
            </ClusterProvider>
          </TRPCReactProvider>
        </StyledComponents>
      </body>
    </html>
  )
}
